Lightweight dark mode
fastify/website-metalsmith pull request #167
Opened 2020-05-04 16:55 UTC by anthonyringoet

Added a lightweight dark mode. Can certainly be improved, only used some CSS overrides.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

2020-05-04 16:55 UTC, anthonyringoet commented
Linking to #79

2020-05-04 16:57 UTC, anthonyringoet commented
![Screenshot_2020-05-04 Fastify, Fast and low overhead web framework, for Node js](https://user-images.githubusercontent.com/576905/80991936-11bb7780-8e39-11ea-9bcd-b4c6004c32b8.png)

2020-05-04 19:01 UTC, StarpTech requested changes

2020-05-04 19:01 UTC, StarpTech commented on src/website/content/css/style.scss
> +@media (prefers-color-scheme: dark) {
I'd prefer a solution with css variables

```css
@media (prefers-color-scheme: dark) {
	:root {
	  --main-bg-color: dark;
	}

}
```

2020-05-05 13:07 UTC, mcollina approved these changes
lgtm

2020-05-05 14:43 UTC, anthonyringoet commented on src/website/content/css/style.scss
> +@media (prefers-color-scheme: dark) {
This is possible for the custom CSS like overriding body background. To override the third-party CSS (eg. Bulma panel and card) you'll still have to overwrite the imported rules afaik. Bulma supports customization but only at compile time with SASS variables afaik.

Is that what you're aiming for here?

2020-05-05 15:24 UTC, StarpTech commented on src/website/content/css/style.scss
> +@media (prefers-color-scheme: dark) {
I agree but did you try this

```scss
// create css variables
$black_value:        hsl(0, 0%, 4%) !default;
// assign css property to bulma variables
$black:         var(--color-black);


// Framework code will work with css property notation
div {
  background-color: #{$black};
}
// Framework code end

// Create css variables
:root {
  --color-black: #{$black_value};
}
```

produces

```scss
div {
  background-color: var(--color-black);
}

:root {
  --color-black: #0a0a0a;
}
```

this should work as long as no other transform functions are applied on `$black`

2021-09-25 08:12 UTC, zekth commented
@anthonyringoet could you rebase it and land this? Also we might want a switch for light/dark theme in the future

2021-09-28 18:34 UTC, anthonyringoet commented
@zekth rebased the changes from upstream, feel free to check again

2021-09-28 18:43 UTC, zekth approved these changes

2021-09-28 18:44 UTC, zekth commented
@StarpTech can you recheck it?

2021-09-29 07:16 UTC, anthonyringoet commented
@StarpTech @zekth No need to waste your time rechecking it. FYI, only had time to rebase and check these incoming changes. Did not have the time to add the requested changes.

2023-06-27 12:17 UTC, Eomm commented
Closing for https://github.com/fastify/website-next

2023-06-27 12:17 UTC, closed without merging