Global CTO Forum prefers Fastify. Thank you for developing Fastify.
fastify/website-metalsmith pull request #185
Opened 2020-08-04 13:04 UTC by tolunayakbulut

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

2020-08-04 14:00 UTC, jsumners requested changes

2020-08-04 14:00 UTC, jsumners commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
This file should be removed.

2020-08-04 14:00 UTC, jsumners commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should be removed.

2020-08-04 14:00 UTC, jsumners commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should be removed.

2020-08-04 14:00 UTC, jsumners commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should be removed.

2020-08-04 14:00 UTC, jsumners commented on .idea/website.iml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should be removed.

2020-08-04 14:00 UTC, jsumners commented on .idea/.gitignore
> +/httpRequests/
This file should be removed.

2020-08-04 14:06 UTC, mcollina approved these changes
lgtm

2020-08-04 14:07 UTC, tolunayakbulut commented
> lgtm

Thanks a lot

2020-08-04 14:14 UTC, tolunayakbulut commented
Thanks a lot have a nice day

> On 4 Aug 2020, at 17:06, Matteo Collina <notifications@github.com> wrote:
> 
> 
> @mcollina approved this pull request.
> 
> lgtm
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/fastify/website/pull/185#pullrequestreview-460845981>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AHSKLW4ZZAKOS33O27SK7U3R7AIXPANCNFSM4PUMDEZQ>.
>

2020-08-05 07:15 UTC, mcollina commented
@tolunayakbulut could you please remove the .idea folder? Thanks

2020-08-05 08:06 UTC, tolunayakbulut commented
> @tolunayakbulut could you please remove the .idea folder? Thanks

thanks for your feedback. removed this

2020-08-05 08:08 UTC, mcollina commented
`.idea/workspace.xml` is still there.

2020-08-05 08:17 UTC, merged