Fix home's TypesScript example
fastify/website-metalsmith pull request #209
Opened 2020-10-25 19:36 UTC by pgcalixto

Fix:
- `fastify({})` is not a function, `fastify.fastify({})` is.
- Directly accessing the port via `server.server.address().port`
  would lead to a type error. `server.server.address()` has type
  `string | AddressInfo`, and `string` does not have the `port`
  property. The new cast prevents this error.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2020-10-25 19:38 UTC, pgcalixto commented
Instead of

```ts
const { port } = server.server.address() as {
  address: string;
  family: string;
  port: number;
}

server.log.info(`server listening on ${port}`)
```

I could do

```ts
server.log.info(`server listening on ${(server.server.address() as any).port}`)
```

which is much simpler for a very quick example. However, enforcing the casting to `any` is not a good practice.

2020-10-25 19:46 UTC, pgcalixto commented
Also, could a maintainer add a `hacktoberfest-accepted` label to this PR, please?

I noticed this issue with the TypeScript documentation while looking to contribute to https://github.com/fastify/fastify, which has the "hacktoberfest" in its topics. However, this repo (https://github.com/fastify/website) does not have "hacktoberfest" as a topic.

Thanks!

2020-10-26 07:02 UTC, mcollina commented
I think we should change this so it uses `import fastify from 'fastify'` instead, and avoid require altogether.

---

@fastify/typescript this keeps coming up, and _it is not correct_. I'd not recommend to add that additional `fastify` property to anyone. If we need to change the types, let's change the types.

2020-10-26 07:09 UTC, fox1t commented
@pgcalixto how did you imported fastify? Top level Fastify import is callable, both in CJS and in TS modules. 


@mcollina we need the named export fastify because it is the only one importable in typed CJS (JS checked by TS compiler). 

In TS the most straightforward way to use the package, is to import Fastify from 'fastify'.

2020-10-26 09:44 UTC, pgcalixto commented
@fox1t, I imported just like the example on the website home.

```ts
import * as fastify from 'fastify'

const server: fastify.FastifyInstance = fastify({})
```

I am using:

- Linux Mint 20
- bash 5.0.17
- Node 12.19.0
- TypeScript 4.0.3

and when I ran tsc, it threw this error:

```
 pedro  ~  projects  fastify-test-ts  npm run build

> fastify-test@1.0.0 build /home/pedro/projects/fastify-test-ts
> tsc

index.ts:4:41 - error TS2349: This expression is not callable.
  Type 'typeof import("/home/pedro/projects/fastify-test-ts/node_modules/fastify/fastify")' has no call signatures.

4 const server: fastify.FastifyInstance = fastify({})
                                          ~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fastify-test@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the fastify-test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pedro/.npm/_logs/2020-10-26T09_28_38_519Z-debug.log
```

My `index.ts` is the same as found on the website home:

```ts
import * as fastify from 'fastify'

const server: fastify.FastifyInstance = fastify({}) // fastify.fastify({})

const opts: fastify.RouteShorthandOptions = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          pong: {
            type: 'string'
          }
        }
      }
    }
  }
}

server.get('/ping', opts, async (request, reply) => {
  return { pong: 'it worked!' }
})

server.listen(3000, (err, address) => {
  if (err) {
    server.log.error(err)
    process.exit(1)
  }

  const { port } = server.server.address() as {
    address: string;
    family: string;
    port: number;
  }

  server.log.info(`server listening on ${port}`)
})
```

Also, my `tsconfig.json` is the default one when I run `npx typescript --init` (I removed all the commented lines auto-generated to be easier):

```js
{
  "compilerOptions": {
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "strict": true,                           /* Enable all strict type-checking options. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}
```

2020-10-26 10:00 UTC, pgcalixto commented
Couldn't we do this intead?

```diff
diff --git a/index.ts b/index.ts
index 2037b53..75975be 100644
--- a/index.ts
+++ b/index.ts
@@ -1,8 +1,8 @@
-import * as fastify from 'fastify'
+import Fastify, { FastifyInstance, RouteShorthandOptions } from 'fastify'
 
-const server: fastify.FastifyInstance = fastify({})
+const server: FastifyInstance = Fastify({})
 
-const opts: fastify.RouteShorthandOptions = {
+const opts: RouteShorthandOptions = {
   schema: {
     response: {
       200: {
```

2020-10-26 10:25 UTC, fox1t commented
There is an error in that docs. You can fix them using your suggestion. Would you mind to check if the error is present in other places?

Thanks for pointing this out.

2020-10-26 10:26 UTC, fox1t commented
In addition to that, you can use the official ts-config for fastify projects: https://www.npmjs.com/package/fastify-tsconfig :)

2020-10-26 11:57 UTC, RafaelGSS commented
May we add some section to explain this behavior, get all content that we have, and place there. Open a discussion with that would be amazing.

2020-10-26 15:51 UTC, fox1t commented
I think that this is just related to TS: in addition to that a namespace (star import), it shouldn't be ever callable in TS.
Do you think adding a new section to explain all of the possible modules contexts?

2020-10-27 03:44 UTC, pgcalixto commented
> You can fix them using your suggestion.

Thanks, @fox1t! I applied my suggestion and committed it.

> Would you mind to check if the error is present in other places?

I search for all the parts of the documentation that had references to TypeScript, and also I checked all examples in the TypeScript section (https://www.fastify.io/docs/latest/TypeScript), and they all seem to be ok.
Though, while reading the documentation, I noticed that the Markdown list items are not aligned, and submitted a PR for the maintainers to check if it is a valid concern: https://github.com/fastify/fastify/pull/2652.

> Do you think adding a new section to explain all of the possible modules contexts?

Doesn't this section resolve it? https://www.fastify.io/docs/latest/TypeScript/#how-to-import

2020-10-27 12:57 UTC, RafaelGSS commented on src/website/layouts/home.html
> +  const { port } = server.server.address() as {
I would change to the [example](https://github.com/fastify/fastify#example) on fastify
```js
  fastify.log.info(`server listening on ${address}`)
```

2020-10-27 13:05 UTC, pgcalixto commented on src/website/layouts/home.html
> +  const { port } = server.server.address() as {
I thought about it too, but I decided to maintain the `${server.server.address().port}` logic because the other examples in the website home use this logic too.

In both "Quick start" and "Request/Response validation and hooks" sections of https://www.fastify.io/, they log `${server.server.address().port}`, not `address`.

2020-10-27 13:11 UTC, pgcalixto commented
I just noticed something, too:

Both "Quick start" and "Request/Response validation and hooks" examples in the website home (https://www.fastify.io/) have async / await examples, which start the server like this:

```javascript
// async version
fastify.listen(3000, (err) => {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${fastify.server.address().port}`)
})
```

```javascript
// await version
const start = async () => {
  try {
    await fastify.listen(3000)
    fastify.log.info(`server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}
start()
```

However, the "Typescript Support" example uses callback in both async / await examples:

```javascript
server.listen(3000, (err) => {
  if (err) {
    server.log.error(err)
    process.exit(1)
  }
  server.log.info(`server listening on ${server.server.address().port}`)
})
```

I'll try to fix it.

2020-10-27 13:13 UTC, pgcalixto commented on src/website/layouts/home.html
> +  server.log.info(`server listening on ${port}`)
Change it to use an async function: https://github.com/fastify/website/pull/209#issuecomment-717232755.

2020-10-30 23:16 UTC, pgcalixto commented on src/website/layouts/home.html
> +  server.log.info(`server listening on ${port}`)
Fixed it.

2020-10-31 09:42 UTC, mcollina commented
The build seems failing.

2020-10-31 10:43 UTC, lmammino commented
having a look at the build, at first glance it seems unrelated to what's changed by this pr

2020-10-31 11:41 UTC, lmammino commented
Hey @pgcalixto, if you get the latest changes from `master` in this branch, that should address the issue with the failing build.

2020-10-31 11:48 UTC, pgcalixto commented
Build is passing now.

2020-11-01 02:45 UTC, Ethan-Arrowood requested changes

2020-11-01 02:45 UTC, Ethan-Arrowood commented on src/website/layouts/home.html
> +    const { port } = server.server.address() as {
this part should be necessary. `address()` returns `string | AddressInfo`. Id rather see some sort of type checking/defaulting here than an `as` cast.

2020-11-01 10:44 UTC, pgcalixto commented on src/website/layouts/home.html
> +    const { port } = server.server.address() as {
The problem is that `string` does not have the `port` property. Also, `AddressInfo` is not exported by net module of `@types/node` (that's why I wrote it). How could we do it without a cast?

When using the home's example (without the cast), tsc throws the error below:

```bash
index.ts:35:42 - error TS2339: Property 'port' does not exist on type 'string | AddressInfo'.
  Property 'port' does not exist on type 'string'.

35     const port = server.server.address().port
                                            ~~~~
```

2020-11-02 16:02 UTC, Ethan-Arrowood commented on src/website/layouts/home.html
> +    const { port } = server.server.address() as {
```ts
const address = server.server.address()
const port = typeof address === 'string' ? address : address.port
```

2020-11-02 16:20 UTC, fox1t commented on src/website/layouts/home.html
> +    const { port } = server.server.address() as {
I can confirm that the cast is mandatory. @Ethan-Arrowood your suggestion is interesting though.
Do we know in which cases the `address()` call returns a plain string?

2020-11-02 16:21 UTC, Ethan-Arrowood commented on src/website/layouts/home.html
> +    const { port } = server.server.address() as {
Another thing we can do here is contribute to net types and export that interface.

Also can use one of the new nullish coalescing features

2020-11-03 00:38 UTC, pgcalixto commented on src/website/layouts/home.html
> +    const { port } = server.server.address() as {
From [Node.js' documentation about server.address()](https://nodejs.org/docs/latest-v14.x/api/net.html#net_server_address):

> Returns the bound address, the address family name, and port of the server as reported by the operating system if listening on an IP socket.
> For a server listening on a pipe or Unix domain socket, the name is returned as a string.

In summary, if the socket is an API socket, it returns an object. If the server is listening to a pipe or Unix domain socket, it returns a string.

In Fastify's case, I guess it'll always be an object. However, we still need to do a type guarding / casting, for TypeScript to correctly transpile it.

2020-11-03 00:43 UTC, pgcalixto commented on src/website/layouts/home.html
> +    const { port } = server.server.address() as {
Indeed it was better to use a type guard than casting, @Ethan-Arrowood. Changed it now.

2020-11-03 00:44 UTC, Ethan-Arrowood approved these changes
LGTM! Great work on this

2020-11-03 08:09 UTC, merged