Changed text to icons as links for profiles
fastify/website-metalsmith pull request #213
Opened 2020-11-08 17:17 UTC by PratikLomte

Hey there!
When I first visited the website https://www.fastify.io/ I found that it is very well organized and smoothly transcends through different sections. However, when I reached the the team segment I saw this
![image](https://user-images.githubusercontent.com/66465662/98471594-6f2ee780-2213-11eb-8de5-1980ee0927b1.png)
For the profile links, text was used. I think we can replace text by icons, it would be more aesthetic. I have attempted to do exactly that. So this is my vision
![image](https://user-images.githubusercontent.com/66465662/98471579-50305580-2213-11eb-837d-6a612b89f46f.png)
For the GitHub and Twitter icons I have used their respective icons from font awesome but I couldn't find anything useful for npm so I created an image instead and used it here as an icon.

2020-11-08 19:05 UTC, mcollina approved these changes
lgtm

2020-11-08 19:05 UTC, mcollina approved these changes
lgtm

2020-11-09 01:18 UTC, jsumners reviewed
`alt` attributes should be added for screen readers.

2020-11-18 19:05 UTC, mcollina commented
@lmammino could you take a look while the build is failing?

2021-01-26 17:45 UTC, mcollina requested changes

2021-01-26 17:45 UTC, mcollina commented on src/website/layouts/home.html
> -                      {% endfor %}
you are missing a matching `endfor`.

2021-01-26 17:45 UTC, mcollina commented on src/website/layouts/home.html
> +                      {% if {{ label }} == 'github' %}
I think the syntax for this is not correct, it should not have `{{ label }}` but `label`

Anyway, check it on https://mozilla.github.io/nunjucks/templating.html#if

2021-01-28 09:43 UTC, lmammino requested changes
Hello @PratikLomte and apologies for my delayed review 😭 

I would prefer to have a consistent set of icons before we carry on with these changes.

With those we could also simplify the code as i mentioned in this review.

Makes sense?

I'll try to make quick research for icons that we might use, but feel free to pick one if there is a good icon set that you know and like particularly.

2021-01-28 09:43 UTC, lmammino commented on src/website/layouts/home.html
> +                          <img src="./src/website/content/images/npm.png" width="30" height="20" alt="Fastify"/>
Can we use an svg rather than a png? Also, can we make sure we use a consistent set of icons?

2021-01-28 09:43 UTC, lmammino commented on src/website/layouts/home.html
> +                      {% if {{ label }} == 'github' %}
I think that if we generalise the approach (e.g. only using svgs or only using font-awesome font icons), we can generalise this code and that we don't need to do 3 separate branches:

```jinja
{% set icons={twitter:"twitter-icon.svg", npm:"npm-icon.svg", github: "github-icon.svg"} %}

{% for label, link in member.links %}
  <a href="{{ link }}" target="_blank"><img src="{{icons[label]}}" alt="{{ label }}"/></a>	
{% endfor %}
```

if we have consistent file names, we probably can avoid also the lookup table and just interpolate the `label` to create the path to the icon.

2021-01-28 09:48 UTC, lmammino commented
The build fails for some syntax error. You can do

```bash
npm install
npm run start:dev
```

if you want to test your code locally before pushing changes

2021-01-28 09:54 UTC, lmammino commented
Btw i am quite liking the svgs from https://jam-icons.com/


<img width="98" alt="Screenshot 2021-01-28 at 09 50 19" src="https://user-images.githubusercontent.com/205629/106120521-62ed6300-614e-11eb-9102-a865620799a1.png">
<img width="91" alt="Screenshot 2021-01-28 at 09 50 11" src="https://user-images.githubusercontent.com/205629/106120537-6680ea00-614e-11eb-9452-9fd6a47ad759.png">
<img width="99" alt="Screenshot 2021-01-28 at 09 50 03" src="https://user-images.githubusercontent.com/205629/106120547-697bda80-614e-11eb-95a9-397146e3bb15.png">


Since you can copy the svg markup from every icon we could easily keep them in line in the page and void additional network connections.

so something like this could just work:

```jinja
{% set svgicons={
  twitter:'<svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -4 24 24" width="24" height="24" preserveAspectRatio="xMinYMin" class="icon__icon"><path d="M20 1.907a8.292 8.292 0 0 1-2.356.637A4.07 4.07 0 0 0 19.448.31a8.349 8.349 0 0 1-2.607.98A4.12 4.12 0 0 0 13.846.015c-2.266 0-4.103 1.81-4.103 4.04 0 .316.036.625.106.92A11.708 11.708 0 0 1 1.393.754a3.964 3.964 0 0 0-.554 2.03c0 1.403.724 2.64 1.824 3.363A4.151 4.151 0 0 1 .805 5.64v.05c0 1.958 1.415 3.591 3.29 3.963a4.216 4.216 0 0 1-1.08.141c-.265 0-.522-.025-.773-.075a4.098 4.098 0 0 0 3.832 2.807 8.312 8.312 0 0 1-5.095 1.727c-.332 0-.658-.02-.979-.056a11.727 11.727 0 0 0 6.289 1.818c7.547 0 11.673-6.157 11.673-11.496l-.014-.523A8.126 8.126 0 0 0 20 1.907z"></path></svg>',
  npm: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -8 24 24" width="24" height="24" preserveAspectRatio="xMinYMin" class="icon__icon"><path d="M0 0h20v6.857H10V8H5.556V6.857H0V0zm1.111 5.714h2.222V2.286h1.111v3.428h1.112V1.143H1.11v4.571zm5.556-4.571v5.714h2.222V5.714h2.222V1.143H6.667zm5.555 0v4.571h2.222V2.286h1.112v3.428h1.11V2.286h1.112v3.428h1.11V1.143h-6.666z"></path><path d="M10 4.7H9V2.2h1z"></path></svg>',
  github: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -2 24 24" width="24" height="24" preserveAspectRatio="xMinYMin" class="icon__icon"><path d="M18.88 1.099C18.147.366 17.265 0 16.233 0H3.746C2.714 0 1.832.366 1.099 1.099.366 1.832 0 2.714 0 3.746v12.487c0 1.032.366 1.914 1.099 2.647.733.733 1.615 1.099 2.647 1.099H6.66c.19 0 .333-.007.429-.02a.504.504 0 0 0 .286-.169c.095-.1.143-.245.143-.435l-.007-.885c-.004-.564-.006-1.01-.006-1.34l-.3.052c-.19.035-.43.05-.721.046a5.555 5.555 0 0 1-.904-.091 2.026 2.026 0 0 1-.872-.39 1.651 1.651 0 0 1-.572-.8l-.13-.3a3.25 3.25 0 0 0-.41-.663c-.186-.243-.375-.407-.566-.494l-.09-.065a.956.956 0 0 1-.17-.156.723.723 0 0 1-.117-.182c-.026-.061-.004-.111.065-.15.07-.04.195-.059.378-.059l.26.04c.173.034.388.138.643.311a2.1 2.1 0 0 1 .631.677c.2.355.44.626.722.813.282.186.566.28.852.28.286 0 .533-.022.742-.065a2.59 2.59 0 0 0 .585-.196c.078-.58.29-1.028.637-1.34a8.907 8.907 0 0 1-1.333-.234 5.314 5.314 0 0 1-1.223-.507 3.5 3.5 0 0 1-1.047-.872c-.277-.347-.505-.802-.683-1.365-.177-.564-.266-1.215-.266-1.952 0-1.049.342-1.942 1.027-2.68-.32-.788-.29-1.673.091-2.652.252-.079.625-.02 1.119.175.494.195.856.362 1.086.5.23.14.414.257.553.352a9.233 9.233 0 0 1 2.497-.338c.859 0 1.691.113 2.498.338l.494-.312a6.997 6.997 0 0 1 1.197-.572c.46-.174.81-.221 1.054-.143.39.98.424 1.864.103 2.653.685.737 1.028 1.63 1.028 2.68 0 .737-.089 1.39-.267 1.957-.177.568-.407 1.023-.689 1.366-.282.343-.633.63-1.053.865-.42.234-.828.403-1.223.507a8.9 8.9 0 0 1-1.333.235c.45.39.676 1.005.676 1.846v3.11c0 .147.021.266.065.357a.36.36 0 0 0 .208.189c.096.034.18.056.254.064.074.01.18.013.318.013h2.914c1.032 0 1.914-.366 2.647-1.099.732-.732 1.099-1.615 1.099-2.647V3.746c0-1.032-.367-1.914-1.1-2.647z"></path></svg>'
} %}

{% for label, link in member.links %}
  <a href="{{ link }}" target="_blank">{{svgicons[label] | safe}}</a>	
{% endfor %}
```

2021-01-28 12:38 UTC, jsumners commented on src/website/layouts/home.html
> +                          <img src="./src/website/content/images/npm.png" width="30" height="20" alt="Fastify"/>
https://simpleicons.org

2021-02-02 16:10 UTC, mcollina commented
@PratikLomte could you please use the icons that @lmammino has identified in https://github.com/fastify/website/pull/213#issuecomment-768936362?

2021-02-02 16:41 UTC, lmammino commented
> @PratikLomte could you please use the icons that @lmammino has identified in [#213 (comment)](https://github.com/fastify/website/pull/213#issuecomment-768936362)?

I personally also like the ones that @jsumners  recommended above (https://simpleicons.org).

In fairness, I am fine with whatever consistent icon set, as long as the file format is SVG. At that point, we can easily embed the markup directly in the page and avoid unnecessary network requests at page load.

Let me know if that makes sense, I am happy to help more if needed.

2021-02-03 09:27 UTC, lmammino commented
Hey @PratikLomte, great job and thanks for being patient with the reviews :)
I will just do some minor touch-ups and get this merged!

2021-02-03 09:55 UTC, PratikLomte commented
Like I said in the beginning together we can make it happen and we did it! 

Thank you @lmammino for helping me out all the way!
And also thank you @mcollina for this opportunity and all the guidance you have given along the way and not to forget @jsumners for the suggestions

It is a great experience working with you all!

2021-02-03 09:58 UTC, lmammino commented
Hey i did some minor improvements:

- changed npm logo for a square alternative which fits bettter with the design (IMHO)
- made the color of the links consistent and added brand logo on hover
- added tooltips

### Preview

![Kapture 2021-02-03 at 09 56 03](https://user-images.githubusercontent.com/205629/106730176-3336d300-6606-11eb-8436-39302d458bdf.gif)

@PratikLomte, @jsumners, @mcollina, what do you think?

I am personally happy to merge it at this point :)

2021-02-03 10:00 UTC, lmammino approved these changes

2021-02-03 13:03 UTC, jsumners requested changes
A wayward `npm.png` is still in this PR.

Also, how are attributing the source of these icons? I do not see any link back to the source in the svg blocks. I'm not even clear which set we ended up choosing (I have no real care which) from the discussion in the PR.

2021-02-04 09:49 UTC, mcollina approved these changes
lgtm

2021-02-04 09:51 UTC, mcollina commented
> A wayward `npm.png` is still in this PR.

I can't see this, link?

> Also, how are attributing the source of these icons? I do not see any link back to the source in the svg blocks. I'm not even clear which set we ended up choosing (I have no real care which) from the discussion in the PR.

@PratikLomte ??

2021-02-04 12:22 UTC, jsumners commented
> I can't see this, link?


![image](https://user-images.githubusercontent.com/321201/106892152-ab120580-66b9-11eb-9032-06876396b646.png)

2021-02-04 18:33 UTC, lmammino commented
I did manually edit the npm icon. For the other 2, @PratikLomte which set did you end up using? We could add a mention in the footer of the website.

2021-02-04 18:35 UTC, lmammino commented
Also removed the unnecessary png. Thanks a lot, @jsumners for spotting that!

2021-02-04 18:40 UTC, PratikLomte commented
> I did manually edit the npm icon. For the other 2, @PratikLomte which set did you end up using? We could add a mention in the footer of the website.

Just like you suggested @lmammino I have used svg icons from https://simpleicons.org/. In the beginning I couldn't find anything useful for npm so I had created a image to be used as a link. But as it is not required now you did the right thing to remove it

2021-02-04 18:42 UTC, lmammino commented
Awesome, let me add a mention to them in our footer and i think we could be in a good position to ship this :)

2021-02-04 18:47 UTC, lmammino commented
Done

<img width="1376" alt="Screenshot 2021-02-04 at 18 46 33" src="https://user-images.githubusercontent.com/205629/106940352-5b632680-6719-11eb-9a14-1d297d66f4fc.png">

2021-02-04 18:48 UTC, lmammino commented
@jsumners, what do you think? :)

2021-02-04 19:06 UTC, jsumners approved these changes
LGTM

2021-02-04 19:15 UTC, merged