feat: add sfits to organizations
fastify/website-metalsmith pull request #247
Opened 2021-03-29 10:13 UTC by fschaeffler

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-03-29 13:07 UTC, jsumners commented on src/website/content/images/organisations/sfits.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 49 50" width="50" height="50"><style>.st1{fill:#eea100;stroke:#fff;stroke-width:.25;stroke-miterlimit:10}</style><rect width="100%" height="100%"
@lmammino this logo has color. Does our website desaturate color logos? Or do they need to be added without color?

2021-03-29 17:00 UTC, lmammino commented on src/website/content/images/organisations/sfits.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 49 50" width="50" height="50"><style>.st1{fill:#eea100;stroke:#fff;stroke-width:.25;stroke-miterlimit:10}</style><rect width="100%" height="100%"
sorry for the late reply on this. There shouldn't be any problem with colors. We do use a CSS filter to saturate the images to greyscale and then we show colors only on mouse hover

2021-03-29 17:03 UTC, jsumners approved these changes
LGTM

2021-03-29 17:23 UTC, RafaelGSS approved these changes
LGTM.

2021-03-30 15:14 UTC, mcollina approved these changes
lgtm

2021-03-30 15:16 UTC, mcollina requested changes
This looks a lot like a website of a single freelancer. I don't think we should endorse this on our website. The proper way for individuals to promote themselves is as collaborators.

2021-03-30 15:32 UTC, jsumners commented
> This looks a lot like a website of a single freelancer. I don't think we should endorse this on our website. The proper way for individuals to promote themselves is as collaborators.

I can accept that rule.

2021-03-30 16:51 UTC, fschaeffler commented
> This looks a lot like a website of a single freelancer. I don't think we should endorse this on our website. The proper way for individuals to promote themselves is as collaborators.

Yes, this is right. I'm a single freelancer and I'm specialised in scalable high traffic back-ends with a good focus towards AWS. For example, the last one I did that also included Fastify in some form has peaks of up to 100k RPS. Unfortunately, I'm not much of an open source contributor for Fastify as a lot of my work is under strict NDAs.

2021-03-30 17:56 UTC, closed without merging

2021-03-30 17:59 UTC, fschaeffler commented
You're totally right. This doesn't fit here as I'm not an organisation.