Fix/docs resources folder
fastify/website-metalsmith pull request #249
Opened 2021-04-02 16:08 UTC by arkerone

This PR should fix the issue reported in #225

The SVG images are optimized and I get this 
![image](https://user-images.githubusercontent.com/9639876/113432743-3c61d780-93de-11eb-9615-70836a074acc.png)

Should I turn off optimization for the resource folder? or is this another issue?

2021-04-02 16:38 UTC, mcollina approved these changes
lgtm

2021-04-02 22:05 UTC, jsumners requested changes
> Should I turn off optimization for the resource folder?

Please turn off optimization. The SVG should not look like your screenshot. You can see what it should look like by viewing the same document in the main Fastify repo.

2021-04-02 23:02 UTC, arkerone commented
> > Should I turn off optimization for the resource folder?
> 
> Please turn off optimization. The SVG should not look like your screenshot. You can see what it should look like by viewing the same document in the main Fastify repo.

I've fixed it!

2021-04-02 23:04 UTC, jsumners approved these changes
Amazing work! Thank you for fixing this big issue.

@lmammino does the local preview look right to you?

2021-04-03 14:29 UTC, lmammino commented on src/scripts/buildWebsite.js
> +      pattern: ['**/*.{js,css,png,jpg,svg}', '!**/resources/*.*']
Why are we disabling content hashing for these resources? If they change these assets, the old version will stay in the CDN cache and we won't be able to see the updated version.

2021-04-03 14:38 UTC, lmammino reviewed
I can confirm the SVG looks good locally. Thanks a lot, @arkerone for all the good work!

I am still concerned about the lack of content hashing though.

I'd say, either we find a way to reference the image directly from GitHub or, if we prefer to copy the asset into the website, then we need to keep content hashing to allow us to invalidate the cache in case we decide to update the image.

2021-04-03 15:09 UTC, arkerone commented on src/scripts/buildWebsite.js
> +      pattern: ['**/*.{js,css,png,jpg,svg}', '!**/resources/*.*']
I didn't find out how to use the hash via the `hashes` metadata object. I'll investigate to resolve this problem.

2021-04-03 23:57 UTC, arkerone commented
I've fixed it. We can use the hash version of images.

2021-04-06 10:05 UTC, arkerone commented
I think everything seems good. Tell me if anything is missing or is a problem

2021-04-06 12:01 UTC, jsumners commented
I'm sure @lmammino will re-review when he is able.

2021-04-06 13:25 UTC, lmammino commented on src/plugins/metalsmith-nunjucks-renderer.js
> +const extname = require('path').extname
Why do we need this plugin?

2021-04-06 13:28 UTC, lmammino approved these changes
Looks good! Thanks for the great contribution @arkerone!

I have left only one minor question

2021-04-06 13:59 UTC, arkerone commented on src/plugins/metalsmith-nunjucks-renderer.js
> +const extname = require('path').extname
It's to use the hashed version of images via the `hashes` metadata object (ie: in html `{{hashes[url}}`). When the markdown is converted in html, I use a custom renderer for image and I transform the URL like that :`<img src="/{{ hashes['${href}'] }}" alt="${title}" title="${title}" />`, then we need to use nunjunks to render the correct url via this hashes object which is injected in this plugin.

2021-04-06 16:54 UTC, lmammino commented on src/plugins/metalsmith-nunjucks-renderer.js
> +const extname = require('path').extname
Oh right! I think I see now. Very clever :)

2021-04-06 16:55 UTC, merged

2021-04-06 16:59 UTC, lmammino commented
It's live! https://www.fastify.io/docs/latest/Encapsulation/

Thanks again @arkerone!

2021-04-06 17:13 UTC, arkerone commented
> It's live! https://www.fastify.io/docs/latest/Encapsulation/
> 
> Thanks again @arkerone!

Great, good news  ! Thanks :+1: