add reference at fastify-cli
fastify/website-metalsmith pull request #330
Opened 2022-02-08 18:32 UTC by marcodev86

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-02-09 08:09 UTC, Fdawgs requested changes

2022-02-09 08:09 UTC, Fdawgs commented on src/website/layouts/home.html
> +        <pre><code class="shell">npm install fastify-cli</code></pre>
Needs a global option, because if the user attempts to run the next step it will error as the `fastify` command cannot be found.

2022-02-09 16:12 UTC, marcodev86 commented
You are right. Fixed

2022-02-09 16:38 UTC, Fdawgs approved these changes

2022-02-09 23:48 UTC, LANCENET reviewed
viewed

2022-02-13 09:06 UTC, luisorbaiceta commented
@marcodev86 could you please address the heading issue so we can merge the PR? thanks!

2022-02-13 10:54 UTC, marcodev86 commented
> @marcodev86 could you please address the heading issue so we can merge the PR? thanks!

Hi @luisorbaiceta , 
now I have added the reference at issue, on the first post, is that right in this way ?

2022-02-14 09:56 UTC, luisorbaiceta commented
Hi @marcodev86, sorry if I didn't explain myself. What I'm referring to is that the title you added `Using CLI`, instead of being an `h1`, it should follow the hierarchy and be an `h2`

2022-02-14 23:11 UTC, marcodev86 commented
Oh I didn't understand, I changed the header @luisorbaiceta

2022-02-15 00:57 UTC, luisorbaiceta approved these changes
👌

2022-02-15 00:57 UTC, luisorbaiceta commented on src/website/layouts/home.html
> +        <h1>Using CLI</h1>
As this title is part of the `Quick Start` section, following the hierarchy, this element should be `h2`

2022-02-15 00:57 UTC, luisorbaiceta commented on src/website/layouts/home.html
> +        <pre><code class="shell">npm install fastify-cli</code></pre>
I wonder if we should add an example using `npx` too

2022-02-15 00:58 UTC, merged