Optimize `<img />` loading 🖼️
fastify/website-metalsmith pull request #372
Opened 2022-09-25 15:27 UTC by sanjaiyan-dev

Optimize `<img />` loading 🖼️ 

- [Lazy loading the image](https://web.dev/lazy-loading-images/#images-inline-browser-level)
- [Adding `decoding` attr to `<img />` element.](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decoding)

2022-09-25 15:36 UTC, sanjaiyan-dev commented
> Optimize `<img />` loading 🖼️ 
> 
> - [Lazy loading the image](https://web.dev/lazy-loading-images/#images-inline-browser-level)
> - [Adding `decoding` attr to `<img />` element.](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decoding)

For more information about lazy loading -:
https://web.dev/browser-level-image-lazy-loading

2022-09-26 06:01 UTC, luisorbaiceta commented
Does not affect large contentful paint so I agree with parallelizing and lazy loading the assets. It does affect cumulative layout shift  in the organizations page though. Could you fix that? The height property will let the browser know beforehand how much space has to save to avoid this issue

2022-09-26 07:09 UTC, mcollina approved these changes
lgtm

2022-09-26 12:50 UTC, jsumners commented
> The height property will let the browser know beforehand how much space has to save to avoid this issue

Yes please. I really dislike it when a site shifts around because image heights were not specified.

2022-09-27 13:09 UTC, sanjaiyan-dev commented
Hope I did it correctly :)

2022-09-27 13:38 UTC, Uzlopak commented on src/website/layouts/organisations.html
> +								<img height="60" src="/{{ hashes['images/organisations/' + organization.image] }}" alt="{{ organization.name }} is using Fastify" loading="lazy" decoding="async" />
isnt this set by css?

2022-09-27 16:13 UTC, luisorbaiceta commented on src/website/layouts/organisations.html
> +								<img height="60" src="/{{ hashes['images/organisations/' + organization.image] }}" alt="{{ organization.name }} is using Fastify" loading="lazy" decoding="async" />
https://web.dev/optimize-cls/

2022-09-27 19:52 UTC, luisorbaiceta requested changes

2022-09-27 19:52 UTC, luisorbaiceta commented on src/website/layouts/organisations.html
> +								<img height="60" src="/{{ hashes['images/organisations/' + organization.image] }}" alt="{{ organization.name }} is using Fastify" loading="lazy" decoding="async" />
`width` needs to be set too to fully prevent CLS. Lets see if with `160` we get a good generic aspect ratio

2022-09-27 19:54 UTC, luisorbaiceta requested changes

2022-09-27 19:54 UTC, luisorbaiceta commented on src/website/layouts/organisations.html
> +								<img height="60" src="/{{ hashes['images/organisations/' + organization.image] }}" alt="{{ organization.name }} is using Fastify" loading="lazy" decoding="async" />
`width` needs to be set too, to fully prevent CLS. Lets see if with `160` we get a good generic aspect ratio for the logos

2022-09-28 06:51 UTC, luisorbaiceta commented on src/website/layouts/organisations.html
> +								<img height="60" src="/{{ hashes['images/organisations/' + organization.image] }}" alt="{{ organization.name }} is using Fastify" loading="lazy" decoding="async" />
Digging further I've found that either we set a container with a fixed aspect ratio and make the logos fill or we target the image logos like this:

```css
.logo-img {
  aspect-ratio: attr(width) / attr(height);
}
```

2022-09-30 10:25 UTC, sanjaiyan-dev commented on src/website/layouts/organisations.html
> +								<img height="60" src="/{{ hashes['images/organisations/' + organization.image] }}" alt="{{ organization.name }} is using Fastify" loading="lazy" decoding="async" />
> `width` needs to be set too, to fully prevent CLS. Lets see if with `160` we get a good generic aspect ratio for the logos

Done 🤝

2022-09-30 12:32 UTC, luisorbaiceta approved these changes
👌

2022-09-30 12:33 UTC, merged