Explain when to use fastify in a new FAQ section
fastify/website-metalsmith pull request #411
Opened 2023-06-14 08:09 UTC by binarykitchen

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-06-14 20:14 UTC, Eomm requested changes
I don't think this section has a real value tbh

Moreover, this repo is going to be archived in 1 or 2 weeks due: https://github.com/fastify/website-next

2023-06-14 20:14 UTC, Eomm commented on README.md
> +  1. **Why is the public Fastify site not running on Fastify when you are promoting it?**
It is not a "Frequently Asked Questions" - nobody asked for it before. I think the opened issue is enough here

2023-06-14 20:14 UTC, Eomm commented on README.md
> +  Take a step back. Know your problems first. Compare these with our advantages + disadavantages.
This does not answer - it is a general programming rule to use the right tool for the right task

2023-06-14 20:14 UTC, Eomm commented on README.md
> +  Sure. Just think twice, then submit a [new issue](https://github.com/fastify/website/issues) and formulate well. We will reply :)
In the main repo we have this section:
https://github.com/fastify/fastify#support
and in the website we have this `help` button:

<img width="759" alt="image" src="https://github.com/fastify/website/assets/11404065/1da702dc-5a5d-4e43-ac8a-b7aee359839b">

2023-06-15 06:40 UTC, binarykitchen commented
Good points, and didn't know a new website was coming soon. 
Never mind, let's close, and thanks for your feedback.

2023-06-15 06:40 UTC, closed without merging