Added Algolia search bar
fastify/website-metalsmith pull request #66
Opened 2018-06-28 13:57 UTC by lmammino

As per title

![kapture 2018-06-28 at 14 54 45](https://user-images.githubusercontent.com/205629/42038616-4c3d86fc-7ae3-11e8-88c3-1ba57ffbe6e3.gif)

Not sure how/when the actual docuemnts will be indexed, I believe I can't see anything just yet because I am trying from localhost. @mcollina do you know more about this?

2018-06-28 19:52 UTC, mcollina commented
You might be able to try this by adding a line to your `/etc/hosts` that resolves `www.fastify.io` to `localhost`. 

I'm also ok in landing this and redirect if this does not work.

2018-06-28 19:53 UTC, mcollina commented
I'll also ping them to see!

2018-06-28 20:21 UTC, lmammino commented
@mcollina, Let me try the localhost option and let's see what happens :)

2018-06-28 21:01 UTC, lmammino commented
It doesn't work either. I have a feeling they wait to see they will scrape the original domain to see if their js file has been included as proof of ownership before starting to index all the content.

Do you want to give it a live try?

2018-06-28 21:07 UTC, mcollina commented
let’s wait for them and see what they say!
Il giorno gio 28 giu 2018 alle 23:01 Luciano Mammino <
notifications@github.com> ha scritto:

> It doesn't work either. I have a feeling they wait to see they will scrape
> the original domain to see if their js file has been included as proof of
> ownership before starting to index all the content.
>
> Do you want to give it a live try?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/fastify/website/pull/66#issuecomment-401172087>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AADL4wVOe3-Ail2lMCWFF_yqqWiTbQKjks5uBUQigaJpZM4U7cI0>
> .
>

2018-06-28 22:23 UTC, lmammino commented
Cool ;)

Looking forward to see what they say!

2018-06-28 22:30 UTC, lmammino commented
@mcollina, actually, it seems very likely we have to provide the indexing by ourselves. Ref docs [here](https://www.algolia.com/doc/tutorials/search-ui/autocomplete/auto-complete/).

If that's really the case, this is a bit of extra work that we have to figure out, but gives us the opportunity to be more in control of the indexing.

2018-06-29 07:01 UTC, s-pace commented
👋 

You might need to replace the $VERSION and $TAGS variable. Since the [`facetFilters` ](https://www.algolia.com/doc/api-reference/api-parameters/facetFilters/)are wrong, it reduces the scope to records matching "$VERSION" and "$TAGS", this is why you have no result.

I have tried it and everything should work as expected.

Let us know if you need anything.

2018-06-29 07:01 UTC, s-pace requested changes

2018-06-29 07:01 UTC, s-pace commented on src/website/layouts/default.html
> +        algoliaOptions: { 'facetFilters': ["version:$VERSION", "tags:$TAGS"] },
You need to replace the `$VERSION` and `$TAGS`:

- Replace `$VERSION` with the version you want to search on.
   The list of possible version is hardcoded in the config.
   So as of today you have: `latest`, `master`

- Replace `$TAGS` with the tags you want to search on.
   The list of possible tags is hardcoded in the config.
   So as of today you have: `docs`, `ecosystem`, `home`

2018-06-29 07:01 UTC, s-pace commented on src/website/layouts/default.html
> +        algoliaOptions: { 'facetFilters': ["version:$VERSION", "tags:$TAGS"] },
For example if you want to refine the search to the version "latest" and the tags "docs" just specify:
```js
'facetFilters': ["version:latest", "tags:docs"]
```

2018-06-30 14:59 UTC, mcollina approved these changes
LGTM if it works

2018-06-30 15:00 UTC, lmammino commented
Fantastic, thanks a million @s-pace, this works auto-magically™️ 🤩

![kapture 2018-06-30 at 15 58 05](https://user-images.githubusercontent.com/205629/42126335-b67b4da0-7c7e-11e8-8df0-70bc2c28f09c.gif)

2018-06-30 15:01 UTC, lmammino commented
@mcollina, check the GIF above, I'd be super happy to merge it! :)

2018-06-30 15:04 UTC, mcollina commented
Go ahead! It’s fantastic!

2018-06-30 15:07 UTC, merged

2018-07-02 10:05 UTC, delvedor commented
That's awesome, thanks!